const DEMO = {
  owner: 'northstar-labs',
  repos: [
    { name:'signal-console', fullName:'northstar-labs/signal-console', description:'Realtime observability workspace for small teams.', language:'TypeScript', stars:128, forks:14, openIssues:8, updatedAt:'2026-08-08T05:42:00Z', url:'https://github.com', issues:[{number:241,title:'Add keyboard shortcuts to command palette',labels:['enhancement','planned'],updatedAt:'2026-08-07T10:20:00Z'},{number:236,title:'Persist selected workspace across reloads',labels:['bug','in-progress'],updatedAt:'2026-08-06T09:02:00Z'},{number:228,title:'Document plugin lifecycle hooks',labels:['docs'],updatedAt:'2026-08-04T08:20:00Z'}], releases:[{tag:'v2.4.0',name:'Signal Console 2.4',publishedAt:'2026-08-05T09:00:00Z'},{tag:'v2.3.2',name:'Patch release',publishedAt:'2026-07-29T09:00:00Z'}] },
    { name:'prompt-atlas', fullName:'northstar-labs/prompt-atlas', description:'A versioned library of production-ready prompts.', language:'Python', stars:84, forks:9, openIssues:5, updatedAt:'2026-08-07T14:20:00Z', url:'https://github.com', issues:[{number:97,title:'Add evaluation set for tool routing',labels:['roadmap','planned'],updatedAt:'2026-08-07T08:12:00Z'},{number:92,title:'Fix token counter for cached input',labels:['bug'],updatedAt:'2026-08-02T10:20:00Z'}], releases:[{tag:'v1.8.0',name:'Evaluation toolkit',publishedAt:'2026-07-31T09:00:00Z'}] },
    { name:'local-bridge', fullName:'northstar-labs/local-bridge', description:'Secure local adapters for developer tools.', language:'Go', stars:41, forks:5, openIssues:3, updatedAt:'2026-08-06T17:15:00Z', url:'https://github.com', issues:[{number:33,title:'Add Claude Code usage adapter',labels:['in-progress','integration'],updatedAt:'2026-08-06T07:03:00Z'}], releases:[{tag:'v0.9.1',name:'Windows path handling',publishedAt:'2026-07-25T09:00:00Z'}] }
  ], fetchedAt: null
};
const DEMO_USAGE = {
  codex: { todayTokens: 184000, monthTokens: 2960000, budgetTokens: 4400000, sessions: 17, source:'demo', reset:'2d 14h' },
  claude: { todayTokens: 127000, monthTokens: 2180000, budgetTokens: 3600000, sessions: 12, source:'demo', reset:'—' },
  daily: [36,52,44,61,48,76,68,83,70,88,64,92,74,82],
  models: [{name:'Claude Sonnet',value:48,color:'blue'},{name:'GPT-5-Codex',value:37,color:'teal'},{name:'Claude Opus',value:15,color:'amber'}]
};

const state = { view:'overview', githubView:'all', selectedRepo:'all', github: load('northstar.github', DEMO), usage: load('northstar.usage', DEMO_USAGE), config: load('northstar.config', {owner:'',repos:'',token:'',profileName:'Taofan'}), lastSync:null };
const $ = selector => document.querySelector(selector);
const fmt = number => new Intl.NumberFormat('zh-CN').format(Math.round(number));
const short = number => number >= 1000000 ? `${(number/1000000).toFixed(1)}M` : number >= 1000 ? `${(number/1000).toFixed(0)}K` : String(number);
const dateFmt = value => value ? new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric'}).format(new Date(value)) : '—';
const ago = value => { if (!value) return '—'; const hours = Math.max(1, Math.round((Date.now()-new Date(value))/3600000)); return hours < 24 ? `${hours}h ago` : `${Math.round(hours/24)}d ago`; };
function load(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function toast(message) { const node=$('#toast'); node.textContent=message; node.classList.add('show'); setTimeout(()=>node.classList.remove('show'),2800); }
function pct(value,total) { return total ? Math.min(100, Math.round(value/total*100)) : 0; }
function profileName() { return state.config.profileName || 'Taofan'; }
function greeting() { const hour=new Date().getHours(); if(hour<5) return '夜深了'; if(hour<12) return '早上好'; if(hour<18) return '下午好'; return '晚上好'; }

function render() { renderNav(); renderProfile(); renderOverview(); renderGithubV3(); renderUsage(); renderSettings(); }
function renderProfile() { $('#workspaceLabel').textContent=`${profileName()} 的工作台`; $('#avatarButton').textContent=profileName().trim().charAt(0).toUpperCase() || 'T'; }
function renderNav() { const titles={overview:'总览',github:'GitHub 项目',usage:'AI 使用量',settings:'设置'}; $('#pageTitle').textContent=titles[state.view]; document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===state.view)); document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active-view',view.id===`view-${state.view}`)); }
function header(eyebrow,title,sub,action='') { return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`; }
function metric(label,value,foot,cls='') { return `<div class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-foot ${cls}">${foot}</div></div>`; }
function limitRows(name, limits) { if(!limits) return `<li><span>${name}</span><span>本地日志未提供 limit</span></li>`; const primary=limits.primary; const secondary=limits.secondary; const credits=limits.credits; const reset=value=>value?new Date(value).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'; return `${primary?`<li><span>${name} · ${primary.windowMinutes===300?'5h':'Weekly'}</span><span>${primary.usedPercent??'—'}% · reset ${reset(primary.resetsAt)}</span></li>`:''}${secondary?`<li><span>${name} · Weekly</span><span>${secondary.usedPercent??'—'}% · reset ${reset(secondary.resetsAt)}</span></li>`:''}${credits?`<li><span>${name} · Credits</span><span>${credits.unlimited?'unlimited':credits.balance??'—'}</span></li>`:''}<li><span>${name} · Plan</span><span>${limits.planType||'—'}</span></li>`; }
function budgetInsight(u) { const codexLimit=u.codex.limits?.primary; const total=(u.codex.monthTokens||0)+(u.claude.monthTokens||0); const tokenBudget=(u.codex.budgetTokens||0)+(u.claude.budgetTokens||0); const tokenPct=pct(total,tokenBudget); const avg=(u.daily||[]).slice(0,-1).reduce((s,v)=>s+v,0)/Math.max(1,(u.daily||[]).length-1); const today=(u.daily||[]).at(-1)||0; const credits=u.codex.limits?.credits; const reset=codexLimit?.resetsAt?new Date(codexLimit.resetsAt).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'; if(codexLimit?.usedPercent!=null){ const used=Math.round(codexLimit.usedPercent); const notes=[]; if(used>=95) notes.push(`Codex ${codexLimit.windowMinutes===300?'5h':'weekly'} limit 已接近或达到上限，优先处理短任务，长上下文任务等 reset ${reset} 后再跑。`); else if(used>=80) notes.push(`Codex limit 已使用 ${used}%，建议把大规模重构和长 CI 修复留到 reset 后。`); else notes.push(`Codex limit 当前 ${used}%，还有余量，适合继续承接实现和排错任务。`); if(credits?.hasCredits) notes.push(`credits balance ${credits.balance ?? '—'}，超过 included limit 后可能会消耗 credits。`); if(today>avg*2&&avg>0) notes.push('今日用量显著高于近 14 日均值，建议检查是否有长上下文或重复自动任务。'); if(!u.claude.limits) notes.push('Claude Code subscription limit 本地不可见，因此 Claude 只参与 token 趋势，不参与官方 limit 占比。'); return {label:'Codex Limit',value:`${used}%`,foot:`reset ${reset}`,cls:used>=80?'warn':'good',note:notes.join(' ')}; } return {label:'预算消耗',value:`${tokenPct}%`,foot:`剩余 ${short(Math.max(0,tokenBudget-total))} tokens`,cls:tokenPct>80?'warn':'good',note:`未读取到官方 limit 快照，当前使用自定义 token budget 估算。${today>avg*2&&avg>0?' 今日用量显著高于近 14 日均值，建议检查长上下文任务。':''}`}; }
function repoRow(repo) { return `<div class="repo-row"><div class="repo-icon">⌘</div><div class="repo-main"><div class="repo-name">${repo.name}</div><div class="repo-desc">${repo.description}</div></div><div class="repo-stat">${repo.openIssues ?? '—'}<small>OPEN ISSUES</small></div><div class="repo-stat">${repo.stars ?? '—'}<small>STARS</small></div><span class="health"></span></div>`; }
function releaseRow(release,repoName) { return `<div class="release-row"><div class="release-date">${dateFmt(release.publishedAt)}</div><span class="release-dot"></span><div class="release-name"><b>${release.name}</b><small style="display:block;color:#71809b;margin-top:3px">${repoName}</small></div><span class="release-tag">${release.tag}</span></div>`; }

function renderOverview() {
  const repos=state.github.repos||[]; const issues=repos.reduce((sum,repo)=>sum+(repo.openIssues||0),0); const releases=repos.flatMap(r=>(r.releases||[])).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)); const aiToday=(state.usage.codex.todayTokens||0)+(state.usage.claude.todayTokens||0); const recentIssues=repos.flatMap(repo=>(repo.issues||[]).map(issue=>({...issue,repo:repo.name}))).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,4);
  const insight=budgetInsight(state.usage);
  $('#view-overview').innerHTML = header('PERSONAL OPERATING SYSTEM',`${greeting()}，${escapeHtml(profileName())}`,'把代码进度和 AI 资源放在同一个视野里。',`<div class="heading-actions"><div class="date-chip">${new Intl.DateTimeFormat('zh-CN',{weekday:'short',month:'short',day:'numeric'}).format(new Date())}</div><button class="danger-button" id="shutdownApp">关闭程序</button></div>`) + `<div class="metric-grid">${metric('活跃项目',repos.length,`${repos.filter(r=>r.openIssues>0).length} 个有待办`, 'good')}${metric('开放 Issue',issues,`${recentIssues.length} 条最近有更新`,issues>12?'warn':'good')}${metric('最近版本',releases.length,`${releases[0]?dateFmt(releases[0].publishedAt):'暂无'} 最近发布`,'good')}${metric('今日 AI Token',short(aiToday),`Codex ${short(state.usage.codex.todayTokens)} · Claude ${short(state.usage.claude.todayTokens)}`,'') }</div><div class="content-grid"><div><div class="panel"><div class="panel-header"><div><div class="panel-title">项目脉搏</div><div class="panel-subtitle">${repos.length} 个仓库 · 过去 24 小时内的状态</div></div><button class="text-button" data-go="github">查看全部 →</button></div>${repos.slice(0,4).map(repoRow).join('')||'<div class="empty">暂无项目数据，请到设置中连接 GitHub。</div>'}</div><div class="panel"><div class="panel-header"><div><div class="panel-title">版本时间线</div><div class="panel-subtitle">最近发布的版本</div></div><button class="text-button" data-go="github">发布记录 →</button></div>${releases.slice(0,4).map(r=>releaseRow(r,'')).join('')||'<div class="empty">暂无 Release 数据。</div>'}</div></div><div><div class="panel usage-card"><div class="panel-header"><div><div class="panel-title">AI 资源分配</div><div class="panel-subtitle">本月累计 · 两个工具</div></div><span class="source-pill"><i></i> ${state.usage.codex.source==='demo'?'演示':'已连接'}</span></div><div class="usage-total"><strong>${short((state.usage.codex.monthTokens||0)+(state.usage.claude.monthTokens||0))}</strong><span>TOKENS</span></div><div class="usage-bar"><div class="usage-fill" style="width:${Math.min(100,Number.parseInt(insight.value)||0)}%"></div></div><div class="usage-labels"><span>${escapeHtml(insight.label)}</span><span>${escapeHtml(insight.value)} · ${escapeHtml(insight.foot)}</span></div><div class="budget-note">${escapeHtml(insight.note)}</div></div><div class="panel"><div class="panel-header"><div><div class="panel-title">最近活动</div><div class="panel-subtitle">Issue 和计划动态</div></div></div>${recentIssues.map(issue=>`<div class="activity"><div class="activity-icon">${issue.labels?.includes('bug')?'△':'＋'}</div><div class="activity-main"><b>#${issue.number} ${issue.title}</b><br><span style="color:#71809b">${issue.repo}</span></div><div class="activity-time">${ago(issue.updatedAt)}</div></div>`).join('')||'<div class="empty">暂无活动。</div>'}</div></div></div>`;
  document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.go)));
}

function renderGithub() {
  const repos=state.github.repos||[]; const allIssues=repos.flatMap(repo=>(repo.issues||[]).map(issue=>({...issue,repo:repo.name}))); const closedIssues=repos.flatMap(repo=>(repo.closedIssues||[]).map(issue=>({...issue,repo:repo.name}))); const buckets={planned:[],progress:[],review:[],done:closedIssues}; allIssues.forEach(issue=>{ const labels=(issue.labels||[]).join(' ').toLowerCase(); if(labels.includes('review')) buckets.review.push(issue); else if(labels.includes('in-progress')||labels.includes('doing')) buckets.progress.push(issue); else buckets.planned.push(issue); });
  const issueCard=issue=>`<div class="roadmap-item">#${issue.number} ${issue.title}<small>${issue.repo} · ${(issue.labels||[]).slice(0,2).join(' / ')||'unlabelled'}</small></div>`;
  $('#view-github').innerHTML=header('DELIVERY CENTER','GitHub 项目','版本、Issue 和轻量项目计划的统一视图。',`<button class="primary-button" id="githubSync">↻ 同步 GitHub</button>`) + `<div class="filter-row"><button class="filter active">全部项目</button><button class="filter">最近发布</button><button class="filter">计划看板</button></div><div class="repo-grid">${repos.map(repo=>`<div class="panel repo-detail"><div class="repo-top"><div><h3>${repo.name}</h3><p>${repo.description}</p></div><a href="${repo.url||'#'}" target="_blank">OPEN ↗</a></div><div class="detail-stats"><div class="detail-stat"><strong>${repo.openIssues??0}</strong><small>OPEN ISSUES</small></div><div class="detail-stat"><strong>${repo.stars??0}</strong><small>STARS</small></div><div class="detail-stat"><strong>${(repo.releases||[]).length}</strong><small>RELEASES</small></div><div class="detail-stat"><strong>${repo.language||'—'}</strong><small>STACK</small></div></div><div class="tag-list"><span class="tag">${repo.fullName||repo.name}</span><span class="tag">updated ${ago(repo.updatedAt)}</span></div></div>`).join('')||'<div class="panel empty">暂无项目，请到设置中配置 GitHub。</div>'}</div><div class="panel" style="margin-top:17px"><div class="panel-header"><div><div class="panel-title">计划看板</div><div class="panel-subtitle">Open Issues 通过 planned / in-progress / review 标签聚合；Done 来自最近关闭的 Issues</div></div><span class="source-pill"><i></i>${state.github.fetchedAt?'LIVE SYNC':'DEMO DATA'}</span></div><div class="roadmap"><div class="roadmap-col"><h4>Planned <span>${buckets.planned.length}</span></h4>${buckets.planned.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无计划事项</div>'}</div><div class="roadmap-col"><h4>In Progress <span>${buckets.progress.length}</span></h4>${buckets.progress.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无进行中事项</div>'}</div><div class="roadmap-col"><h4>Review <span>${buckets.review.length}</span></h4>${buckets.review.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无 review 事项</div>'}</div><div class="roadmap-col"><h4>Done <span>${buckets.done.length}</span></h4>${buckets.done.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无关闭事项</div>'}</div></div></div>`;
  $('#githubSync').addEventListener('click', syncGithub);
}

function renderGithubV2() {
  const repos=state.github.repos||[];
  const allIssues=repos.flatMap(repo=>(repo.issues||[]).map(issue=>({...issue,repo:repo.name})));
  const closedIssues=repos.flatMap(repo=>(repo.closedIssues||[]).map(issue=>({...issue,repo:repo.name})));
  const buckets={planned:[],progress:[],review:[],done:closedIssues};
  allIssues.forEach(issue=>{ const labels=(issue.labels||[]).join(' ').toLowerCase(); if(labels.includes('review')) buckets.review.push(issue); else if(labels.includes('in-progress')||labels.includes('doing')) buckets.progress.push(issue); else buckets.planned.push(issue); });
  const issueCard=issue=>`<div class="roadmap-item">#${issue.number} ${escapeHtml(issue.title)}<small>${escapeHtml(issue.repo)} · ${(issue.labels||[]).slice(0,2).map(escapeHtml).join(' / ')||'unlabelled'}</small></div>`;
  const ciCard=repo=>{ const ci=repo.latestCi; if(!ci) return '<div class="ci-card"><div><b>CI</b><small>No workflow run</small></div></div>'; const conclusion=ci.conclusion||ci.status||'unknown'; const cls=conclusion==='success'?'good':['failure','timed_out','cancelled'].includes(conclusion)?'bad':'warn'; return `<div class="ci-card"><div><b>${escapeHtml(ci.name||'CI')}</b><small>${escapeHtml(ci.branch||'unknown')} · ${ago(ci.updatedAt)}</small></div><span class="ci-status ${cls}">${escapeHtml(conclusion)}</span>${cls==='bad'?`<button class="ghost-button ci-check" data-repo="${escapeHtml(repo.name)}" data-run="${ci.id}">检查报错</button>`:''}<a href="${ci.url||'#'}" target="_blank">RUN ↗</a></div><div class="ci-errors" id="ci-${escapeHtml(repo.name)}-${ci.id}"></div>`; };
  const repoCard=repo=>`<div class="panel repo-detail"><div class="repo-top"><div><h3>${escapeHtml(repo.name)}</h3><p>${escapeHtml(repo.description)}</p></div><a href="${repo.url||'#'}" target="_blank">OPEN ↗</a></div><div class="detail-stats"><div class="detail-stat"><strong>${repo.openIssues??0}</strong><small>OPEN ISSUES</small></div><div class="detail-stat"><strong>${repo.stars??0}</strong><small>STARS</small></div><div class="detail-stat"><strong>${(repo.releases||[]).length}</strong><small>RELEASES</small></div><div class="detail-stat"><strong>${repo.language||'—'}</strong><small>STACK</small></div></div>${ciCard(repo)}<div class="tag-list"><span class="tag">${escapeHtml(repo.fullName||repo.name)}</span><span class="tag">updated ${ago(repo.updatedAt)}</span></div></div>`;
  $('#view-github').innerHTML=header('DELIVERY CENTER','GitHub 项目','版本、Issue、CI 和轻量项目计划的统一视图。',`<button class="primary-button" id="githubSync">↻ 同步 GitHub</button>`) + `<div class="filter-row"><button class="filter active">全部项目</button><button class="filter">最近发布</button><button class="filter">计划看板</button><button class="filter">CI 状态</button></div><div class="repo-grid">${repos.map(repoCard).join('')||'<div class="panel empty">暂无项目，请到设置中配置 GitHub。</div>'}</div><div class="panel" style="margin-top:17px"><div class="panel-header"><div><div class="panel-title">计划看板</div><div class="panel-subtitle">Open Issues 通过 planned / in-progress / review 标签聚合；Done 来自最近关闭的 Issues</div></div><span class="source-pill"><i></i>${state.github.fetchedAt?'LIVE SYNC':'DEMO DATA'}</span></div><div class="roadmap"><div class="roadmap-col"><h4>Planned <span>${buckets.planned.length}</span></h4>${buckets.planned.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无计划事项</div>'}</div><div class="roadmap-col"><h4>In Progress <span>${buckets.progress.length}</span></h4>${buckets.progress.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无进行中事项</div>'}</div><div class="roadmap-col"><h4>Review <span>${buckets.review.length}</span></h4>${buckets.review.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无 review 事项</div>'}</div><div class="roadmap-col"><h4>Done <span>${buckets.done.length}</span></h4>${buckets.done.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无关闭事项</div>'}</div></div></div>`;
  $('#githubSync').addEventListener('click', syncGithub);
  document.querySelectorAll('.ci-check').forEach(button=>button.addEventListener('click',()=>checkCi(button.dataset.repo,button.dataset.run)));
}

function renderGithubV3() {
  const repos=state.github.repos||[];
  const scopedRepos=state.selectedRepo==='all'?repos:repos.filter(repo=>repo.name===state.selectedRepo);
  if(state.selectedRepo!=='all'&&!scopedRepos.length) state.selectedRepo='all';
  const openIssueCount=scopedRepos.reduce((sum,repo)=>sum+(repo.openIssues||0),0);
  const failedCiCount=scopedRepos.filter(repo=>['failure','timed_out','cancelled'].includes(repo.latestCi?.conclusion)).length;
  const allIssues=scopedRepos.flatMap(repo=>(repo.issues||[]).map(issue=>({...issue,repo:repo.name})));
  const closedIssues=scopedRepos.flatMap(repo=>(repo.closedIssues||[]).map(issue=>({...issue,repo:repo.name})));
  const releases=scopedRepos.flatMap(repo=>(repo.releases||[]).map(release=>({...release,repo:repo.name}))).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt));
  const buckets={planned:[],progress:[],review:[],done:closedIssues};
  allIssues.forEach(issue=>{ const labels=(issue.labels||[]).join(' ').toLowerCase(); if(labels.includes('review')) buckets.review.push(issue); else if(labels.includes('in-progress')||labels.includes('doing')) buckets.progress.push(issue); else buckets.planned.push(issue); });
  const issueCard=issue=>`<div class="roadmap-item">#${issue.number} ${escapeHtml(issue.title)}<small>${escapeHtml(issue.repo)} · ${(issue.labels||[]).slice(0,2).map(escapeHtml).join(' / ')||'unlabelled'}</small></div>`;
  const ciCard=repo=>{ const ci=repo.latestCi; if(!ci) return '<div class="ci-card"><div><b>CI</b><small>No workflow run</small></div></div>'; const conclusion=ci.conclusion||ci.status||'unknown'; const cls=conclusion==='success'?'good':['failure','timed_out','cancelled'].includes(conclusion)?'bad':'warn'; return `<div class="ci-card"><div><b>${escapeHtml(ci.name||'CI')}</b><small>${escapeHtml(ci.branch||'unknown')} · ${ago(ci.updatedAt)}</small></div><span class="ci-status ${cls}">${escapeHtml(conclusion)}</span>${cls==='bad'?`<button class="ghost-button ci-check" data-repo="${escapeHtml(repo.name)}" data-run="${ci.id}">检查报错</button>`:''}<a href="${ci.url||'#'}" target="_blank">RUN ↗</a></div><div class="ci-errors" id="ci-${escapeHtml(repo.name)}-${ci.id}"></div>`; };
  const repoCard=repo=>`<div class="panel repo-detail"><div class="repo-top"><div><h3>${escapeHtml(repo.name)}</h3><p>${escapeHtml(repo.description)}</p></div><a href="${repo.url||'#'}" target="_blank">OPEN ↗</a></div><div class="detail-stats"><div class="detail-stat"><strong>${repo.openIssues??0}</strong><small>OPEN ISSUES</small></div><div class="detail-stat"><strong>${repo.stars??0}</strong><small>STARS</small></div><div class="detail-stat"><strong>${(repo.releases||[]).length}</strong><small>RELEASES</small></div><div class="detail-stat"><strong>${repo.language||'—'}</strong><small>STACK</small></div></div>${ciCard(repo)}<div class="tag-list"><span class="tag">${escapeHtml(repo.fullName||repo.name)}</span><span class="tag">updated ${ago(repo.updatedAt)}</span></div></div>`;
  const roadmap=`<div class="panel"><div class="panel-header"><div><div class="panel-title">计划看板</div><div class="panel-subtitle">Open Issues 通过 planned / in-progress / review 标签聚合；Done 来自最近关闭的 Issues</div></div><span class="source-pill"><i></i>${state.github.fetchedAt?'LIVE SYNC':'DEMO DATA'}</span></div><div class="roadmap"><div class="roadmap-col"><h4>Planned <span>${buckets.planned.length}</span></h4>${buckets.planned.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无计划事项</div>'}</div><div class="roadmap-col"><h4>In Progress <span>${buckets.progress.length}</span></h4>${buckets.progress.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无进行中事项</div>'}</div><div class="roadmap-col"><h4>Review <span>${buckets.review.length}</span></h4>${buckets.review.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无 review 事项</div>'}</div><div class="roadmap-col"><h4>Done <span>${buckets.done.length}</span></h4>${buckets.done.slice(0,5).map(issueCard).join('')||'<div class="empty">暂无关闭事项</div>'}</div></div></div>`;
  const allView=`<div class="metric-grid">${metric('监控项目',scopedRepos.length,state.selectedRepo==='all'?`${repos.length} 个已配置 repo`:'当前项目','good')}${metric('开放 Issue',openIssueCount,`${allIssues.length} 条已拉取 open issue`,openIssueCount>12?'warn':'good')}${metric('最新 Release',releases.length,releases[0]?`${releases[0].repo} · ${dateFmt(releases[0].publishedAt)}`:'暂无发布','good')}${metric('CI 异常',failedCiCount,failedCiCount?'需要检查失败 run':'最新 CI 未发现失败',failedCiCount?'warn':'good')}</div><div class="repo-grid">${scopedRepos.map(repoCard).join('')||'<div class="panel empty">暂无项目，请到设置中配置 GitHub。</div>'}</div>`;
  const releasesView=`<div class="panel"><div class="panel-header"><div><div class="panel-title">最近发布</div><div class="panel-subtitle">${releases.length} 条 release 记录</div></div></div>${releases.map(r=>releaseRow(r,r.repo)).join('')||'<div class="empty">暂无 Release 数据。</div>'}</div>`;
  const ciView=`<div class="repo-grid">${scopedRepos.map(repo=>`<div class="panel repo-detail"><div class="repo-top"><div><h3>${escapeHtml(repo.name)}</h3><p>${escapeHtml(repo.description)}</p></div><a href="${repo.url||'#'}" target="_blank">OPEN ↗</a></div>${ciCard(repo)}<div class="tag-list"><span class="tag">${escapeHtml(repo.fullName||repo.name)}</span></div></div>`).join('')||'<div class="panel empty">暂无 CI 数据。</div>'}</div>`;
  const views={all:allView,releases:releasesView,roadmap,ci:ciView};
  const tabs=[['all','全部项目'],['releases','最近发布'],['roadmap','计划看板'],['ci','CI 状态']];
  const projectSelect=`<div class="github-toolbar"><select id="repoScope"><option value="all">全部项目</option>${repos.map(repo=>`<option value="${escapeHtml(repo.name)}" ${state.selectedRepo===repo.name?'selected':''}>${escapeHtml(repo.name)}</option>`).join('')}</select><button class="primary-button" id="githubSync">↻ 同步 GitHub</button></div>`;
  $('#view-github').innerHTML=header('DELIVERY CENTER','GitHub 项目','版本、Issue、CI 和轻量项目计划的统一视图。',projectSelect) + `<div class="filter-row">${tabs.map(([id,label])=>`<button class="filter ${state.githubView===id?'active':''}" data-github-view="${id}">${label}</button>`).join('')}</div>${views[state.githubView]||views.all}`;
  $('#githubSync').addEventListener('click', syncGithub);
  $('#repoScope').addEventListener('change',event=>{state.selectedRepo=event.target.value; renderGithubV3();});
  document.querySelectorAll('[data-github-view]').forEach(button=>button.addEventListener('click',()=>{state.githubView=button.dataset.githubView; renderGithubV3();}));
  document.querySelectorAll('.ci-check').forEach(button=>button.addEventListener('click',()=>checkCi(button.dataset.repo,button.dataset.run)));
}

function renderUsage() {
  const u=state.usage; const total=u.codex.monthTokens+u.claude.monthTokens; const max=Math.max(...u.daily,1); const models=u.models||DEMO_USAGE.models;
  const insight=budgetInsight(u);
  $('#view-usage').innerHTML=header('RESOURCE BUDGET','AI 使用量','追踪 Codex 与 Claude Code 的本地导入数据，关注节奏而不只是总量。',`<button class="primary-button" id="syncUsage">↻ 读取本地 Usage</button>`) + `<div class="usage-summary">${metric('Codex · 本月',short(u.codex.monthTokens),`${u.codex.sessions} 个 session · reset ${u.codex.reset}`,'good')}${metric('Claude Code · 本月',short(u.claude.monthTokens),`${u.claude.sessions} 个 session · 本地日志`,'good')}${metric(insight.label,insight.value,insight.foot,insight.cls)}</div><div class="content-grid"><div class="panel"><div class="panel-header"><div><div class="panel-title">近 14 日用量趋势</div><div class="panel-subtitle">每日 token 使用量 · 相对值</div></div><div class="legend"><span>总用量</span><span>预算节奏</span></div></div><div class="chart">${u.daily.map((value,index)=>`<div class="bar-col"><div class="bar" style="height:${Math.max(8,value/max*100)}%" title="${value}k"></div><div class="bar-label">${index===u.daily.length-1?'今天':`-${u.daily.length-index-1}d`}</div></div>`).join('')}</div></div><div><div class="panel"><div class="panel-header"><div><div class="panel-title">模型分布</div><div class="panel-subtitle">按 token 估算</div></div></div>${models.map(model=>`<div class="model-line"><span class="model-name">${model.name}</span><div class="model-track"><i style="width:${model.value}%;background:${model.color==='blue'?'var(--blue)':model.color==='amber'?'var(--amber)':'var(--teal)'}"></i></div><span class="model-count">${model.value}%</span></div>`).join('')}<div class="budget-note" style="margin-top:25px">${escapeHtml(insight.note)}</div></div><div class="panel"><div class="panel-header"><div><div class="panel-title">Subscription Limits</div><div class="panel-subtitle">本地日志中可见的窗口、重置和 credits</div></div></div><ul class="info-list">${limitRows('Codex',u.codex.limits)}${limitRows('Claude Code',u.claude.limits)}</ul></div></div></div><div class="panel" style="margin-top:17px"><div class="panel-header"><div><div class="panel-title">数据源状态</div><div class="panel-subtitle">连接方式和最近更新时间</div></div></div><ul class="info-list"><li><span>Codex</span><span>${u.codex.source==='demo'?'演示数据 · 待导入':'本地导入 · 已更新'}</span></li><li><span>Claude Code</span><span>${u.claude.source==='demo'?'演示数据 · 待导入':'本地导入 · 已更新'}</span></li><li><span>计算口径</span><span>token / session / 日趋势 / limit 快照</span></li></ul></div>`;
  $('#syncUsage').addEventListener('click',syncUsage);
  document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.go)));
}

function renderSettings() {
  const c=state.config; $('#view-settings').innerHTML=header('SYSTEM CONFIG','连接与偏好','所有配置仅保存在当前浏览器的本地存储中。',`<span class="source-pill"><i></i> WINDOWS 11 READY</span>`) + `<div class="settings-layout"><div class="panel"><div class="panel-title">GitHub 连接</div><div class="panel-subtitle">用于拉取仓库、Issue、Release；公开仓库可不填 Token</div><div class="field"><label>显示名称</label><input id="profileName" value="${escapeHtml(profileName())}" placeholder="Taofan" /></div><div class="field"><label>GitHub Owner / User</label><input id="configOwner" value="${escapeHtml(c.owner)}" placeholder="例如：octocat" /></div><div class="field"><label>仓库名称（逗号分隔，最多 12 个）</label><input id="configRepos" value="${escapeHtml(c.repos)}" placeholder="例如：hello-world, my-project" /></div><div class="field"><label>Personal Access Token（可选）</label><input id="configToken" type="password" value="${escapeHtml(c.token)}" placeholder="仅保存在本机，不会写入项目文件" /></div><div class="help">建议使用只读权限的 fine-grained token：Metadata: Read、Issues: Read、Contents: Read。服务器只监听 127.0.0.1。</div><div class="settings-actions"><button class="primary-button" id="saveConfig">保存配置</button><button class="ghost-button" id="testGithub">保存并同步</button></div></div><div class="panel"><div class="panel-title">AI 使用量导入</div><div class="panel-subtitle">粘贴 JSON；也可在 AI 使用量页读取本机日志</div><div class="field"><label>Usage JSON</label><textarea id="usageJson" spellcheck="false">${escapeHtml(JSON.stringify(state.usage,null,2))}</textarea></div><div class="help">默认扫描 %USERPROFILE%\\.codex\\sessions 和 %USERPROFILE%\\.claude 下的 JSON/JSONL；也可在启动前设置 CODEX_USAGE_PATH / CLAUDE_USAGE_PATH。数据只存 localStorage。</div><div class="settings-actions"><button class="primary-button" id="importUsage">导入并更新</button><button class="ghost-button" id="loadSample">恢复演示数据</button></div></div></div>`;
  $('#saveConfig').addEventListener('click',saveConfig); $('#testGithub').addEventListener('click',async()=>{saveConfig(); await syncGithub();}); $('#importUsage').addEventListener('click',importUsage); $('#loadSample').addEventListener('click',()=>{state.usage=DEMO_USAGE; save('northstar.usage',state.usage); render(); toast('已恢复演示用量数据');});
}
function escapeHtml(value) { return String(value||'').replace(/[&<>'"]/g, char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
function saveConfig() { state.config={profileName:$('#profileName').value.trim()||'Taofan',owner:$('#configOwner').value.trim(),repos:$('#configRepos').value.trim(),token:$('#configToken').value.trim()}; save('northstar.config',state.config); renderProfile(); toast('配置已保存到本机'); }
function importUsage() { try { const parsed=JSON.parse($('#usageJson').value); if(!parsed.codex||!parsed.claude) throw new Error('需要同时包含 codex 和 claude'); state.usage=parsed; save('northstar.usage',parsed); render(); toast('AI 用量已导入'); } catch(error) { toast(`导入失败：${error.message}`); } }
async function checkCi(repo,runId) { const target=$(`#ci-${repo}-${runId}`); if(!target) return; const {owner,token}=state.config; target.innerHTML='<div class="ci-log">读取 CI 报错中…</div>'; try { const response=await fetch('/api/github-ci',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,repo,runId,token})}); const data=await response.json(); if(!response.ok||data.error) throw new Error(data.error||'读取失败'); const failed=data.failedJobs||[]; target.innerHTML=failed.length?failed.map(job=>`<div class="ci-log"><b>${escapeHtml(job.name)}</b>${(job.failedSteps||[]).map(step=>`<small>Failed step: ${escapeHtml(step.name)} (${escapeHtml(step.conclusion)})</small>`).join('')}${(job.logHighlights||[]).map(line=>`<code>${escapeHtml(line)}</code>`).join('')}<a href="${job.url||'#'}" target="_blank">Open job ↗</a></div>`).join(''):'<div class="ci-log">没有失败 job，可能 run 状态已经恢复。</div>'; } catch(error) { target.innerHTML=`<div class="error-note">CI 报错读取失败：${escapeHtml(error.message)}</div>`; } }
async function syncGithub(options={}) { const {owner,repos,token}=state.config; const silent=options.silent; if(!owner||!repos) { if(!silent) { switchView('settings'); toast('请先配置 GitHub owner 和仓库'); } return false; } $('#syncLabel').textContent='同步中…'; try { const response=await fetch('/api/github',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,repos:repos.split(',').map(item=>item.trim()).filter(Boolean),token})}); const data=await response.json(); if(!response.ok||data.error) throw new Error(data.error||'同步失败'); state.github=data; state.lastSync=new Date(); save('northstar.github',data); $('#syncLabel').textContent='GitHub 已连接'; $('#syncTime').textContent='刚刚同步'; $('#lastSync').textContent=`上次同步 ${state.lastSync.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`; render(); if(!silent) { if(data.errors?.length) toast(`已同步 ${data.repos.length} 个仓库，${data.errors.length} 个失败`); else toast(`已同步 ${data.repos.length} 个 GitHub 仓库`); } return true; } catch(error) { $('#syncLabel').textContent='同步失败'; $('#syncTime').textContent='请检查配置'; if(!silent) toast(`GitHub 同步失败：${error.message}`); return false; } }
async function syncUsage(options={}) { const silent=options.silent; try { const response=await fetch('/api/usage'); const data=await response.json(); if(!response.ok||data.error) throw new Error(data.error||'读取失败'); state.usage=data; save('northstar.usage',data); render(); if(!silent) toast('已读取本地 AI 使用量'); return true; } catch(error) { if(!silent) toast(`Usage 读取失败：${error.message}`); return false; } }
async function autoSync() { $('#syncTime').textContent='自动同步中'; const results=await Promise.all([syncGithub({silent:true}), syncUsage({silent:true})]); const now=new Date(); $('#syncTime').textContent=`自动同步 ${now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`; $('#lastSync').textContent=`自动同步 ${now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`; if(results.some(Boolean)) $('#syncLabel').textContent='数据已更新'; }
async function shutdownApp() { try { await fetch('/api/shutdown',{method:'POST'}); toast('程序正在关闭'); } catch { toast('程序已关闭或连接中断'); } }
function switchView(view) { state.view=view; renderNav(); render(); }
document.addEventListener('click',event=>{ const nav=event.target.closest('.nav-item'); if(nav) switchView(nav.dataset.view); });
$('#refreshButton').addEventListener('click',syncGithub);
document.addEventListener('click',event=>{ if(event.target?.id==='shutdownApp') shutdownApp(); });
render();
setTimeout(autoSync, 10000);
setInterval(autoSync, 5 * 60 * 1000);
