(function () {
  const { escapeHtml, tr, dateText } = window.NorthstarPlannerShared;
  const num = value => Number(value || 0);
  const fitness = data => data.fitness || { profile: null, weightLogs: [], strengthLogs: [], hikes: [], plans: [] };
  const localText = (item, field) => document.documentElement.lang === 'en' && item?.[`${field}En`] ? item[`${field}En`] : item?.[field] || '';
  const localDateTime = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  const recordDate = record => dateText(record.performedAt);
  const legacyExercise = record => ({ exerciseName: record.exerciseName || tr('未命名项目', 'Unnamed exercise'), loadKg: record.loadKg, reps: record.reps, sets: record.sets, setsArePerSide: record.setsArePerSide });
  const exercisesFor = record => Array.isArray(record.exercises) && record.exercises.length ? record.exercises : [legacyExercise(record)];
  const exerciseText = exercise => `${escapeHtml(exercise.exerciseName)} · ${exercise.loadKg} kg · ${exercise.reps}${tr(' 次/组', ' reps/set')} · ${exercise.sets}${exercise.setsArePerSide ? tr(' 组/每侧', ' sets/side') : tr(' 组', ' sets')}`;

  function distribution(data, state) {
    const logs = fitness(data); const last28 = Date.now() - 28 * 86400000;
    const strength = logs.strengthLogs.filter(item => new Date(item.performedAt).getTime() >= last28);
    const hikes = logs.hikes.filter(item => new Date(item.performedAt).getTime() >= last28);
    const count = id => strength.filter(item => item.session === id).length;
    const max = Math.max(1, ...logs.plans.map(plan => count(plan.id)), hikes.length);
    const item = (label, value, cls) => `<div class="fitness-distribution-item"><div><b>${label}</b><span>${value}</span></div><i><em class="${cls}" style="width:${Math.round(value / max * 100)}%"></em></i></div>`;
    const profile = logs.profile || {}; const weights = (logs.weightLogs || []).slice(0, 4);
    const review = state.fitnessReview ? `<div class="fitness-review"><b>${tr('本地 LLM 复盘', 'Local LLM review')}</b><p>${escapeHtml(state.fitnessReview).replace(/\n/g, '<br>')}</p></div>` : '';
    const planDistribution = logs.plans.map((plan, index) => item(escapeHtml(localText(plan, 'name')), count(plan.id), ['a', 'b', 'c'][index % 3])).join('');
    return `<section class="panel fitness-log-panel"><div class="panel-header"><div><div class="eyebrow">TRAINING LOG · LAST 28 DAYS</div><div class="panel-title">${tr('训练分布', 'Training distribution')}</div><div class="panel-subtitle">${tr('基于保存在本机的训练记录。', 'Based on training records saved on this device.')}</div></div><span class="source-pill"><i></i>LOCAL ONLY</span></div><div class="fitness-distribution">${planDistribution}${item(tr('户外活动', 'Outdoor sessions'), hikes.length, 'hike')}</div><div class="fitness-summary"><span>${tr('训练记录', 'Training')} <b>${strength.length}</b></span><span>${tr('户外时长', 'Outdoor time')} <b>${hikes.reduce((sum, entry) => sum + num(entry.durationMinutes), 0)} min</b></span><span>${tr('户外距离', 'Outdoor distance')} <b>${hikes.reduce((sum, entry) => sum + num(entry.distanceKm), 0).toFixed(1)} km</b></span></div><div class="fitness-profile"><input id="fitnessHeight" type="number" min="1" value="${profile.heightCm || ''}" placeholder="${tr('身高 cm', 'Height cm')}"/><input id="fitnessWeight" type="number" min="1" step="0.1" value="${profile.weightKg || ''}" placeholder="${tr('当前体重 kg', 'Current weight kg')}"/><button class="ghost-button fitness-profile-save">${tr('保存身体数据', 'Save profile')}</button><button class="ghost-button fitness-weight-log">${tr('记录体重', 'Log weight')}</button><button class="primary-button fitness-review-button" ${state.llm?.configured ? '' : 'disabled'}>${tr('本地 LLM 复盘', 'Review with local LLM')}</button></div><div class="fitness-weight-history"><b>${tr('体重追踪', 'Weight tracking')}</b>${weights.length ? weights.map(entry => `<span>${recordDate({ performedAt: entry.measuredAt })} · ${entry.weightKg} kg</span>`).join('') : `<span>${tr('记录体重后会在这里形成历史。', 'Weight history appears here after you log it.')}</span>`}</div>${review}</section>`;
  }

  function strengthPlan(plan, index) {
    return `<article class="fitness-plan-card session-${['a', 'b', 'c'][index % 3]}"><div class="fitness-plan-title"><span>${tr('计划', 'PLAN')} ${String(index + 1).padStart(2, '0')}</span><h3>${escapeHtml(localText(plan, 'name'))}</h3></div><p>${escapeHtml(localText(plan, 'focus'))}</p><small>${tr('时长、RPE、质量和酸痛按整个 session 记录；每个动作独立填写。', 'Duration, RPE, quality, and soreness belong to the whole session; exercises are recorded separately.')}</small><button class="ghost-button fitness-log" data-fitness-log="strength" data-session="${escapeHtml(plan.id)}">${tr('记录本次训练', 'Log this session')}</button></article>`;
  }

  function strengthLog(data) {
    const logs = fitness(data).strengthLogs.slice(0, 6);
    const history = logs.length ? logs.map(record => `<div class="fitness-history-row"><span class="fitness-session-pill ${String(record.session).toLowerCase()}">DAY ${escapeHtml(record.session)}</span><div><strong>${recordDate(record)} · ${record.durationMinutes} min</strong><small>${exercisesFor(record).map(exerciseText).join('<br>')}</small><small>RPE ${record.rpe} · ${tr('质量', 'Quality')} ${record.quality}/5 · ${tr('酸痛', 'Soreness')}：24h ${record.soreness24 ?? '—'}/10 · 48h ${record.soreness48 ?? '—'}/10</small>${record.notes ? `<small>${escapeHtml(record.notes)}</small>` : ''}<small><button class="text-button fitness-edit" data-fitness-edit="${escapeHtml(record.id)}">${tr('编辑', 'Edit')}</button> <button class="text-button fitness-delete" data-fitness-delete="${escapeHtml(record.id)}">${tr('删除', 'Delete')}</button></small></div></div>`).join('') : `<div class="empty">${tr('还没有力量训练记录。完成一个 session 后，在这里记录它包含的动作。', 'No strength sessions yet. Record the exercises included after you finish a session.')}</div>`;
    const plans = fitness(data).plans;
    return `<section class="panel fitness-detail-panel"><div class="panel-header"><div><div class="eyebrow">CONFIGURABLE TRAINING</div><div class="panel-title">${tr('训练计划', 'Training plans')}</div><div class="panel-subtitle">${tr('计划内容完全来自本地数据设置。', 'Plan content comes entirely from local data settings.')}</div></div></div><div class="fitness-plan-grid">${plans.map(strengthPlan).join('') || `<div class="empty">${tr('尚未配置训练计划。请在数据设置页添加。', 'No training plans configured. Add one in Data settings.')}</div>`}</div><div class="fitness-history"><b>${tr('最近训练', 'Recent sessions')}</b>${history}</div></section>`;
  }

  function hikeLog(data) {
    const hikes = fitness(data).hikes.slice(0, 6);
    return `<section class="panel fitness-detail-panel"><div class="panel-header"><div><div class="eyebrow">OUTDOOR ACTIVITY</div><div class="panel-title">${tr('户外活动记录', 'Outdoor activity log')}</div></div><button class="ghost-button fitness-log" data-fitness-log="hike">${tr('记录户外活动', 'Log outdoor activity')}</button></div><div class="fitness-history">${hikes.length ? hikes.map(entry => `<div class="fitness-history-row"><span class="fitness-session-pill hike">OUTDOOR</span><div><strong>${recordDate(entry)}</strong><small>${entry.durationMinutes} min · ${entry.distanceKm} km · ${entry.elevationM} m ↑ · RPE ${entry.effort}</small>${entry.notes ? `<small>${escapeHtml(entry.notes)}</small>` : ''}</div></div>`).join('') : `<div class="empty">${tr('还没有户外活动记录。', 'No outdoor activities yet.')}</div>`}</div></section>`;
  }

  function exerciseRow(exercise = {}) {
    const perSide = exercise.setsArePerSide ? ' checked' : '';
    return `<div class="fitness-exercise-row" style="grid-column:span 2;display:grid;grid-template-columns:2fr repeat(3,1fr) auto auto;gap:9px"><input class="fitness-exercise-name" maxlength="120" value="${escapeHtml(exercise.exerciseName || '')}" placeholder="${tr('项目名', 'Exercise')}" /><input class="fitness-exercise-load" type="number" min="0" step="0.5" value="${exercise.loadKg ?? ''}" placeholder="${tr('负重 kg', 'Load kg')}" /><input class="fitness-exercise-reps" type="number" min="0" value="${exercise.reps ?? ''}" placeholder="${tr('每组次数', 'Reps/set')}" /><input class="fitness-exercise-sets" type="number" min="0" value="${exercise.sets ?? ''}" placeholder="${tr('组数', 'Sets')}" /><label><input class="fitness-exercise-per-side" type="checkbox"${perSide} />${tr('每侧', 'Per side')}</label><button type="button" class="text-button fitness-exercise-remove">${tr('移除', 'Remove')}</button></div>`;
  }

  function form(data, state) {
    if (!state.fitnessMode) return '';
    const strength = state.fitnessMode === 'strength';
    const record = state.fitnessRecordId ? fitness(data).strengthLogs.find(entry => entry.id === state.fitnessRecordId) : null;
    const exercises = state.fitnessExercises || (record ? exercisesFor(record) : [{}]);
    const value = (field, fallback = '') => record?.[field] ?? fallback;
    const session = state.fitnessSession || record?.session || '';
    const plan = fitness(data).plans.find(item => item.id === session);
    const heading = strength ? `${record ? tr('编辑', 'Edit') : tr('记录', 'Log')} ${localText(plan, 'name') || session}` : tr('记录户外活动', 'Log outdoor activity');
    return `<div class="fitness-modal-backdrop"><section class="fitness-entry panel"><div class="panel-header"><div><div class="eyebrow">LOCAL TRAINING LOG</div><div class="panel-title">${escapeHtml(heading)}</div></div><button class="text-button fitness-close">${tr('关闭', 'Close')}</button></div><div class="fitness-form"><input id="fitnessPerformedAt" type="datetime-local" value="${record ? new Date(record.performedAt).toISOString().slice(0, 16) : localDateTime()}" />${strength ? `<input id="fitnessDuration" type="number" min="0" value="${value('durationMinutes')}" placeholder="${tr('整个 session 时长（分钟）', 'Whole-session duration (min)')}" /><div id="fitnessExercises" style="grid-column:span 2;display:grid;gap:9px">${exercises.map(exerciseRow).join('')}</div><button type="button" class="ghost-button fitness-exercise-add">${tr('添加动作', 'Add exercise')}</button><input id="fitnessRpe" type="number" min="0" max="10" step="0.5" value="${value('rpe')}" placeholder="${tr('整个 session 的 RPE 0–10', 'Whole-session RPE 0–10')}" /><input id="fitnessQuality" type="number" min="0" max="5" step="1" value="${value('quality')}" placeholder="${tr('整体动作质量 0–5', 'Overall quality 0–5')}" /><input id="fitnessSoreness24" type="number" min="0" max="10" step="1" value="${value('soreness24')}" placeholder="${tr('24h 酸痛 0–10（可留空）', '24h soreness 0–10 (optional)')}" /><input id="fitnessSoreness48" type="number" min="0" max="10" step="1" value="${value('soreness48')}" placeholder="${tr('48h 酸痛 0–10（可留空）', '48h soreness 0–10 (optional)')}" />` : `<input id="fitnessDuration" type="number" min="0" placeholder="${tr('时长（分钟）', 'Duration (min)')}" /><input id="fitnessDistance" type="number" min="0" step="0.1" placeholder="${tr('距离 km', 'Distance km')}" /><input id="fitnessElevation" type="number" min="0" placeholder="${tr('爬升 m', 'Elevation m')}" /><input id="fitnessEffort" type="number" min="0" max="10" step="0.5" placeholder="RPE 0–10" />`}<textarea id="fitnessNotes" placeholder="${tr('动作反馈、左右差异或恢复感受（可选）', 'Technique feedback, asymmetry, or recovery notes (optional)')}">${escapeHtml(value('notes'))}</textarea><button class="primary-button fitness-save" data-mode="${state.fitnessMode}" data-session="${escapeHtml(session)}" data-record-id="${record?.id || ''}">${tr('保存到本机', 'Save locally')}</button></div></section></div>`;
  }

  function render(data, state) { return `${distribution(data, state)}<div class="fitness-section-stack">${strengthLog(data)}${hikeLog(data)}</div>${form(data, state)}`; }
  function resetForm(state) { state.fitnessMode = null; state.fitnessSession = null; state.fitnessRecordId = null; state.fitnessExercises = null; }
  function bind(state, apply, showError) {
    document.querySelectorAll('.fitness-log').forEach(button => button.addEventListener('click', () => { state.fitnessMode = button.dataset.fitnessLog; state.fitnessSession = button.dataset.session || null; state.fitnessRecordId = null; state.fitnessExercises = null; state.render(); }));
    document.querySelectorAll('.fitness-edit').forEach(button => button.addEventListener('click', () => { const record = fitness(state.data).strengthLogs.find(entry => entry.id === button.dataset.fitnessEdit); state.fitnessMode = 'strength'; state.fitnessRecordId = record.id; state.fitnessSession = record.session; state.fitnessExercises = exercisesFor(record); state.render(); }));
    document.querySelectorAll('.fitness-delete').forEach(button => button.addEventListener('click', async () => { if (!window.confirm(tr('删除这条完整 session 记录？此操作无法撤销。', 'Delete this complete session record? This cannot be undone.'))) return; try { await apply([{ type: 'delete_fitness_session', id: button.dataset.fitnessDelete }]); } catch (error) { showError(error.message); } }));
    document.querySelector('.fitness-close')?.addEventListener('click', () => { resetForm(state); state.render(); });
    document.querySelector('.fitness-exercise-add')?.addEventListener('click', () => document.querySelector('#fitnessExercises').insertAdjacentHTML('beforeend', exerciseRow()));
    document.querySelector('#fitnessExercises')?.addEventListener('click', event => { if (event.target.closest('.fitness-exercise-remove')) event.target.closest('.fitness-exercise-row').remove(); });
    document.querySelector('.fitness-profile-save')?.addEventListener('click', async () => { try { await apply([{ type: 'update_fitness_profile', heightCm: document.querySelector('#fitnessHeight').value, weightKg: document.querySelector('#fitnessWeight').value }]); } catch (error) { showError(error.message); } });
    document.querySelector('.fitness-weight-log')?.addEventListener('click', async () => { try { await apply([{ type: 'log_fitness_weight', weightKg: document.querySelector('#fitnessWeight').value, measuredAt: new Date().toISOString() }]); } catch (error) { showError(error.message); } });
    document.querySelector('.fitness-review-button')?.addEventListener('click', async () => { const button = document.querySelector('.fitness-review-button'); button.disabled = true; button.textContent = tr('正在复盘…', 'Reviewing…'); try { const result = await window.NorthstarPlannerShared.request('/api/planner/fitness-review', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); state.fitnessReview = result.review; state.render(); } catch (error) { showError(error.message); button.disabled = false; button.textContent = tr('本地 LLM 复盘', 'Review with local LLM'); } });
    document.querySelector('.fitness-save')?.addEventListener('click', async button => {
      const mode = button.currentTarget.dataset.mode; const value = id => document.querySelector(id).value;
      const shared = { performedAt: value('#fitnessPerformedAt'), durationMinutes: value('#fitnessDuration'), notes: value('#fitnessNotes') };
      const exercises = [...document.querySelectorAll('.fitness-exercise-row')].map(row => { const exerciseName = row.querySelector('.fitness-exercise-name').value; return { exerciseName, loadKg: row.querySelector('.fitness-exercise-load').value, reps: row.querySelector('.fitness-exercise-reps').value, sets: row.querySelector('.fitness-exercise-sets').value, setsArePerSide: row.querySelector('.fitness-exercise-per-side').checked || /单腿|单侧|single[- ]?leg|unilateral/i.test(exerciseName) }; });
      const operation = mode === 'strength' ? { type: button.currentTarget.dataset.recordId ? 'update_fitness_session' : 'log_fitness_session', ...(button.currentTarget.dataset.recordId ? { id: button.currentTarget.dataset.recordId } : {}), plan: 'strength', session: button.currentTarget.dataset.session, ...shared, exercises, rpe: value('#fitnessRpe'), quality: value('#fitnessQuality'), soreness24: value('#fitnessSoreness24'), soreness48: value('#fitnessSoreness48') } : { type: 'log_hike', ...shared, distanceKm: value('#fitnessDistance'), elevationM: value('#fitnessElevation'), effort: value('#fitnessEffort') };
      try { await apply([operation]); resetForm(state); state.render(); } catch (error) { showError(error.message); }
    });
  }
  window.NorthstarPlannerFitness = { render, bind };
}());
