(function () {
  const { escapeHtml, tr, dateText } = window.NorthstarPlannerShared;
  const sessionPlans = {
    A: { title: ['Day A · 臀大肌堆量', 'Day A · Glute max volume'], focus: ['主动作堆积有效训练容量，稳定推进负重或次数。', 'Build quality volume on the main glute movements; progress load or reps steadily.'], cue: ['记录总组数、总次数、负重、RPE；最后一组应保留 1–3 次余力。', 'Track total sets, reps, load and RPE; leave 1–3 reps in reserve on the final set.'] },
    B: { title: ['Day B · 侧臀塑形', 'Day B · Side glute shape'], focus: ['以髋外展与单侧稳定为主，控制骨盆，追求目标肌感。', 'Prioritize abduction and unilateral stability with a controlled pelvis and clear target-muscle feel.'], cue: ['记录动作质量（1–5）和左右差异，避免用下背或髋屈肌代偿。', 'Record movement quality (1–5) and left/right differences; avoid lower-back or hip-flexor compensation.'] },
    C: { title: ['Day C · 整齐与高质量', 'Day C · Quality control'], focus: ['用干净、可控的动作完成臀部训练，把握恢复与技术。', 'Use clean, controlled movements to manage glute work, recovery, and technique.'], cue: ['以动作质量、RPE 和训练感受为优先；疲劳高时主动降载。', 'Prioritize movement quality, RPE and recovery; reduce load when fatigue is high.'] }
  };
  const num = value => Number(value || 0);
  const fitness = data => data.fitness || { profile: null, weightLogs: [], strengthLogs: [], hikes: [] };
  const localDateTime = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  const recordDate = record => dateText(record.performedAt);

  function distribution(data, state) {
    const logs = fitness(data);
    const last28 = Date.now() - 28 * 86400000;
    const strength = logs.strengthLogs.filter(item => new Date(item.performedAt).getTime() >= last28);
    const hikes = logs.hikes.filter(item => new Date(item.performedAt).getTime() >= last28);
    const count = letter => strength.filter(item => item.session === letter).length;
    const max = Math.max(1, count('A'), count('B'), count('C'), hikes.length);
    const item = (label, value, cls) => `<div class="fitness-distribution-item"><div><b>${label}</b><span>${value}</span></div><i><em class="${cls}" style="width:${Math.round(value / max * 100)}%"></em></i></div>`;
    const profile = logs.profile || {}; const weights = (logs.weightLogs || []).slice(0, 4);
    const review = state.fitnessReview ? `<div class="fitness-review"><b>${tr('本地 LLM 复盘', 'Local LLM review')}</b><p>${escapeHtml(state.fitnessReview).replace(/\n/g, '<br>')}</p></div>` : '';
    return `<section class="panel fitness-log-panel"><div class="panel-header"><div><div class="eyebrow">TRAINING LOG · LAST 28 DAYS</div><div class="panel-title">${tr('训练分布', 'Training distribution')}</div><div class="panel-subtitle">${tr('只基于保存在本机的训练记录；有氧不创建 schedule。', 'Based only on records saved on this device; cardio has no schedule.')}</div></div><span class="source-pill"><i></i>LOCAL ONLY</span></div><div class="fitness-distribution">${item('Day A', count('A'), 'a')}${item('Day B', count('B'), 'b')}${item('Day C', count('C'), 'c')}${item(tr('徒步', 'Hikes'), hikes.length, 'hike')}</div><div class="fitness-summary"><span>${tr('力量训练', 'Strength')} <b>${strength.length}</b></span><span>${tr('徒步时长', 'Hiking time')} <b>${hikes.reduce((sum, item) => sum + num(item.durationMinutes), 0)} min</b></span><span>${tr('徒步距离', 'Hiking distance')} <b>${hikes.reduce((sum, item) => sum + num(item.distanceKm), 0).toFixed(1)} km</b></span></div><div class="fitness-profile"><input id="fitnessHeight" type="number" min="1" value="${profile.heightCm || ''}" placeholder="${tr('身高 cm', 'Height cm')}"/><input id="fitnessWeight" type="number" min="1" step="0.1" value="${profile.weightKg || ''}" placeholder="${tr('当前体重 kg', 'Current weight kg')}"/><button class="ghost-button fitness-profile-save">${tr('保存身体数据', 'Save profile')}</button><button class="ghost-button fitness-weight-log">${tr('记本周体重', 'Log weekly weight')}</button><button class="primary-button fitness-review-button" ${state.llm?.configured ? '' : 'disabled'}>${tr('本地 LLM 复盘', 'Review with local LLM')}</button></div><div class="fitness-weight-history"><b>${tr('体重追踪', 'Weight tracking')}</b>${weights.length ? weights.map(item => `<span>${recordDate({ performedAt: item.measuredAt })} · ${item.weightKg} kg</span>`).join('') : `<span>${tr('每周输入一次体重，形成趋势记录。', 'Enter your weight weekly to build a trend.')}</span>`}</div>${review}</section>`;
  }

  function strengthPlan(letter) {
    const plan = sessionPlans[letter];
    return `<article class="fitness-plan-card session-${letter.toLowerCase()}"><div class="fitness-plan-title"><span>DAY ${letter}</span><h3>${tr(...plan.title)}</h3></div><p>${tr(...plan.focus)}</p><small>${tr(...plan.cue)}</small><button class="ghost-button fitness-log" data-fitness-log="strength" data-session="${letter}">${tr('记录本次训练', 'Log this session')}</button></article>`;
  }

  function strengthLog(data) {
    const logs = fitness(data).strengthLogs.slice(0, 6);
    return `<section class="panel fitness-detail-panel"><div class="panel-header"><div><div class="eyebrow">ANAEROBIC FITNESS</div><div class="panel-title">${tr('臀部塑形 · A / B / C 循环', 'Glute shaping · A / B / C cycle')}</div><div class="panel-subtitle">${tr('每个周期依序完成三个 session，不绑定周几；以日志确认实际训练分布。', 'Complete the three sessions in sequence each cycle, without assigning weekdays; logs show the actual distribution.')}</div></div></div><div class="fitness-plan-grid">${strengthPlan('A')}${strengthPlan('B')}${strengthPlan('C')}</div><div class="fitness-history"><b>${tr('最近力量训练', 'Recent strength sessions')}</b>${logs.length ? logs.map(item => `<div class="fitness-history-row"><span class="fitness-session-pill ${String(item.session).toLowerCase()}">DAY ${escapeHtml(item.session)}</span><div><strong>${recordDate(item)}</strong><small>${item.sets}${tr(' 组', ' sets')} · ${item.reps}${tr(' 次', ' reps')} · ${item.loadKg} kg · RPE ${item.rpe} · ${tr('质量', 'quality')} ${item.quality}/5</small><small>${tr('酸痛', 'Soreness')}：24h ${item.soreness24 ?? '—'}/10 · 48h ${item.soreness48 ?? '—'}/10 <button class="text-button fitness-soreness" data-fitness-soreness="${escapeHtml(item.id)}">${tr('补充酸痛', 'Update soreness')}</button></small>${item.notes ? `<small>${escapeHtml(item.notes)}</small>` : ''}</div></div>`).join('') : `<div class="empty">${tr('还没有力量训练记录。完成 Day A、B 或 C 后，在这里留下容量与动作质量。', 'No strength sessions yet. After Day A, B, or C, record volume and movement quality here.')}</div>`}</div></section>`;
  }

  function hikeLog(data) {
    const hikes = fitness(data).hikes.slice(0, 6);
    return `<section class="panel fitness-detail-panel"><div class="panel-header"><div><div class="eyebrow">AEROBIC FITNESS</div><div class="panel-title">${tr('徒步 · 无 schedule', 'Hiking · no schedule')}</div><div class="panel-subtitle">${tr('按状态自由安排；记录实际完成量与体感，而不是制造未完成的日程压力。', 'Plan freely based on readiness; record what happened and how it felt, rather than creating schedule pressure.')}</div></div><button class="ghost-button fitness-log" data-fitness-log="hike">${tr('记录徒步', 'Log a hike')}</button></div><div class="fitness-hike-note"><b>${tr('建议记录', 'Track')}</b><span>${tr('时长、距离、爬升、主观用力程度，以及路线或身体感受。', 'Time, distance, elevation, perceived effort, plus route or body notes.')}</span></div><div class="fitness-history">${hikes.length ? hikes.map(item => `<div class="fitness-history-row"><span class="fitness-session-pill hike">HIKE</span><div><strong>${recordDate(item)}</strong><small>${item.durationMinutes} min · ${item.distanceKm} km · ${item.elevationM} m ↑ · RPE ${item.effort}</small>${item.notes ? `<small>${escapeHtml(item.notes)}</small>` : ''}</div></div>`).join('') : `<div class="empty">${tr('还没有徒步记录。无需安排日期，完成后再添加。', 'No hikes yet. No date needs to be scheduled—add one after you finish.')}</div>`}</div></section>`;
  }

  function form(mode, session, recordId) {
    if (!mode) return '';
    const strength = mode === 'strength'; const sorenessOnly = mode === 'soreness';
    return `<div class="fitness-modal-backdrop"><section class="fitness-entry panel"><div class="panel-header"><div><div class="eyebrow">LOCAL TRAINING LOG</div><div class="panel-title">${sorenessOnly ? tr('补充延迟酸痛', 'Update delayed soreness') : strength ? `${tr('记录 Day', 'Log Day')} ${session}` : tr('记录徒步', 'Log a hike')}</div></div><button class="text-button fitness-close">${tr('关闭', 'Close')}</button></div><div class="fitness-form">${sorenessOnly ? `<input id="fitnessSoreness24" type="number" min="0" max="10" step="1" placeholder="${tr('24h 酸痛 0–10', '24h soreness 0–10')}" /><input id="fitnessSoreness48" type="number" min="0" max="10" step="1" placeholder="${tr('48h 酸痛 0–10', '48h soreness 0–10')}" />` : `<input id="fitnessPerformedAt" type="datetime-local" value="${localDateTime()}" />${strength ? `<input id="fitnessDuration" type="number" min="0" placeholder="${tr('时长（分钟）', 'Duration (min)')}" /><input id="fitnessSets" type="number" min="0" placeholder="${tr('总组数', 'Total sets')}" /><input id="fitnessReps" type="number" min="0" placeholder="${tr('总次数', 'Total reps')}" /><input id="fitnessLoad" type="number" min="0" step="0.5" placeholder="${tr('最高工作负重 kg', 'Working load kg')}" /><input id="fitnessRpe" type="number" min="0" max="10" step="0.5" placeholder="RPE 0–10" /><input id="fitnessQuality" type="number" min="0" max="5" step="1" placeholder="${tr('动作质量 0–5', 'Movement quality 0–5')}" /><input id="fitnessSoreness24" type="number" min="0" max="10" step="1" placeholder="${tr('24h 酸痛 0–10（可留空）', '24h soreness 0–10 (optional)')}" /><input id="fitnessSoreness48" type="number" min="0" max="10" step="1" placeholder="${tr('48h 酸痛 0–10（可留空）', '48h soreness 0–10 (optional)')}" />` : `<input id="fitnessDuration" type="number" min="0" placeholder="${tr('时长（分钟）', 'Duration (min)')}" /><input id="fitnessDistance" type="number" min="0" step="0.1" placeholder="${tr('距离 km', 'Distance km')}" /><input id="fitnessElevation" type="number" min="0" placeholder="${tr('爬升 m', 'Elevation m')}" /><input id="fitnessEffort" type="number" min="0" max="10" step="0.5" placeholder="RPE 0–10" />`}`}${sorenessOnly ? '' : `<textarea id="fitnessNotes" placeholder="${tr('路线、动作反馈、左右差异或恢复感受（可选）', 'Route, technique feedback, asymmetry, or recovery notes (optional)')}"></textarea>`}<button class="primary-button fitness-save" data-mode="${mode}" data-session="${session || ''}" data-record-id="${recordId || ''}">${tr('保存到本机', 'Save locally')}</button></div></section></div>`;
  }
  function render(data, state) { return `${distribution(data, state)}<div class="fitness-section-stack">${strengthLog(data)}${hikeLog(data)}</div>${form(state.fitnessMode, state.fitnessSession, state.fitnessRecordId)}`; }
  function bind(state, apply, showError) {
    document.querySelectorAll('.fitness-log').forEach(button => button.addEventListener('click', () => { state.fitnessMode = button.dataset.fitnessLog; state.fitnessSession = button.dataset.session || null; state.render(); }));
    document.querySelectorAll('.fitness-soreness').forEach(button => button.addEventListener('click', () => { state.fitnessMode = 'soreness'; state.fitnessRecordId = button.dataset.fitnessSoreness; state.render(); }));
    document.querySelector('.fitness-close')?.addEventListener('click', () => { state.fitnessMode = null; state.fitnessSession = null; state.fitnessRecordId = null; state.render(); });
    document.querySelector('.fitness-profile-save')?.addEventListener('click', async () => { try { await apply([{ type: 'update_fitness_profile', heightCm: document.querySelector('#fitnessHeight').value, weightKg: document.querySelector('#fitnessWeight').value }]); } catch (error) { showError(error.message); } });
    document.querySelector('.fitness-weight-log')?.addEventListener('click', async () => { try { await apply([{ type: 'log_fitness_weight', weightKg: document.querySelector('#fitnessWeight').value, measuredAt: new Date().toISOString() }]); } catch (error) { showError(error.message); } });
    document.querySelector('.fitness-review-button')?.addEventListener('click', async () => { const button = document.querySelector('.fitness-review-button'); button.disabled = true; button.textContent = tr('正在复盘…', 'Reviewing…'); try { const result = await window.NorthstarPlannerShared.request('/api/planner/fitness-review', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); state.fitnessReview = result.review; state.render(); } catch (error) { showError(error.message); button.disabled = false; button.textContent = tr('本地 LLM 复盘', 'Review with local LLM'); } });
    document.querySelector('.fitness-save')?.addEventListener('click', async button => {
      const mode = button.currentTarget.dataset.mode; const value = id => document.querySelector(id).value;
      const shared = mode === 'soreness' ? null : { performedAt: value('#fitnessPerformedAt'), durationMinutes: value('#fitnessDuration'), notes: value('#fitnessNotes') };
      const operation = mode === 'soreness' ? { type: 'update_fitness_session', id: button.currentTarget.dataset.recordId, soreness24: value('#fitnessSoreness24'), soreness48: value('#fitnessSoreness48') } : mode === 'strength' ? { type: 'log_fitness_session', plan: 'strength', session: button.currentTarget.dataset.session, ...shared, sets: value('#fitnessSets'), reps: value('#fitnessReps'), loadKg: value('#fitnessLoad'), rpe: value('#fitnessRpe'), quality: value('#fitnessQuality'), soreness24: value('#fitnessSoreness24'), soreness48: value('#fitnessSoreness48') } : { type: 'log_hike', ...shared, distanceKm: value('#fitnessDistance'), elevationM: value('#fitnessElevation'), effort: value('#fitnessEffort') };
      try { await apply([operation]); state.fitnessMode = null; state.fitnessSession = null; state.fitnessRecordId = null; } catch (error) { showError(error.message); }
    });
  }
  window.NorthstarPlannerFitness = { render, bind };
}());
