(function () {
  const shared=window.NorthstarPlannerShared;
  const startOfWeek=value=>{const date=new Date(value||Date.now());date.setHours(0,0,0,0);date.setDate(date.getDate()-((date.getDay()+6)%7));return date;};
  const localInputValue=date=>{const pad=value=>String(value).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;};
  const dayLabel=date=>date.toLocaleDateString(document.documentElement.lang==='en'?'en-AU':'zh-CN',{weekday:'short',month:'numeric',day:'numeric'});
  function weekEvents(events){const start=startOfWeek(),end=new Date(start);end.setDate(end.getDate()+7);return(events||[]).filter(event=>{const value=new Date(event.startAt);return value>=start&&value<end;}).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt));}
  function render(data,state){const start=startOfWeek(),end=new Date(start);end.setDate(end.getDate()+6);const events=weekEvents(data.events);const editing=(data.events||[]).find(event=>event.id===state.editingEventId);const days=Array.from({length:7},(_,index)=>{const date=new Date(start);date.setDate(date.getDate()+index);return date;});const nextStart=editing?new Date(editing.startAt):new Date();if(!editing)nextStart.setMinutes(Math.ceil(nextStart.getMinutes()/30)*30,0,0);const nextEnd=editing?.endAt?new Date(editing.endAt):new Date(nextStart.getTime()+90*60000);
    return `<div class="weekly-hero"><div><div class="eyebrow">WEEKLY EXECUTION PLAN</div><h2>${shared.tr('本周计划','Weekly plan')}</h2><p>${shared.tr('所有日程均可编辑和删除。','Every scheduled block can be edited or removed.')}</p></div><div class="weekly-range"><b>${start.toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'})} — ${end.toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'})}</b><span>${events.length} ${shared.tr('项安排','scheduled blocks')}</span></div></div><div class="weekly-layout"><section class="panel weekly-calendar"><div class="panel-header"><div><div class="panel-title">${shared.tr('周视图','Week view')}</div><div class="panel-subtitle">${shared.tr('建议保留一晚机动时间，避免计划排满。','Keep one evening unallocated as a buffer.')}</div></div></div><div class="weekly-days">${days.map(day=>{const dayEvents=events.filter(event=>new Date(event.startAt).toDateString()===day.toDateString()),today=day.toDateString()===new Date().toDateString();return `<article class="weekly-day ${today?'today':''}"><header><b>${dayLabel(day)}</b><span>${dayEvents.length}</span></header>${dayEvents.map(event=>`<div class="weekly-event"><time>${new Date(event.startAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time><b>${shared.escapeHtml(event.title)}</b>${event.notes?`<small>${shared.escapeHtml(event.notes)}</small>`:''}<span><button class="text-button weekly-edit-event" data-id="${shared.escapeHtml(event.id)}">${shared.tr('编辑','Edit')}</button><button class="text-button planner-delete weekly-delete-event" data-id="${shared.escapeHtml(event.id)}">${shared.tr('删除','Delete')}</button></span></div>`).join('')||`<div class="weekly-day-empty">${shared.tr('留白','Open')}</div>`}</article>`;}).join('')}</div></section><aside class="panel weekly-entry"><div class="eyebrow">${editing?'EDIT TIME BLOCK':'ADD TIME BLOCK'}</div><h3>${editing?shared.tr('编辑日程','Edit schedule'):shared.tr('录入日程','Schedule a block')}</h3><label>${shared.tr('安排内容','Title')}<input id="weeklyEventTitle" value="${shared.escapeHtml(editing?.title||'')}" placeholder="${shared.tr('例如：PMRP 动态分析 Lab','e.g. PMRP dynamic analysis lab')}"/></label><div class="weekly-entry-times"><label>${shared.tr('开始','Starts')}<input id="weeklyEventStart" type="datetime-local" value="${localInputValue(nextStart)}"/></label><label>${shared.tr('结束','Ends')}<input id="weeklyEventEnd" type="datetime-local" value="${localInputValue(nextEnd)}"/></label></div><label>${shared.tr('目标 / 产出','Objective / output')}<textarea id="weeklyEventNotes" maxlength="1000">${shared.escapeHtml(editing?.notes||'')}</textarea></label><button class="primary-button" id="plannerSaveWeeklyEvent">${editing?shared.tr('保存日程','Save schedule'):shared.tr('加入本周计划','Add to weekly plan')}</button>${editing?`<button class="text-button" id="plannerCancelWeeklyEvent">${shared.tr('取消编辑','Cancel editing')}</button>`:''}<div id="plannerPreview"></div></aside></div>`;}
  function bind(state,apply,render,showError){document.querySelector('#plannerSaveWeeklyEvent')?.addEventListener('click',async()=>{const title=document.querySelector('#weeklyEventTitle').value.trim(),startAt=document.querySelector('#weeklyEventStart').value,endAt=document.querySelector('#weeklyEventEnd').value,notes=document.querySelector('#weeklyEventNotes').value.trim();if(!title||!startAt)return showError(shared.tr('请填写安排内容和开始时间。','Add a title and start time.'));if(endAt&&new Date(endAt)<=new Date(startAt))return showError(shared.tr('结束时间必须晚于开始时间。','End time must be after start time.'));try{await apply([{type:state.editingEventId?'update_event':'create_event',...(state.editingEventId?{id:state.editingEventId}:{}),title,notes,startAt,endAt:endAt||null,...(!state.editingEventId?{source:'manual'}:{})}]);state.editingEventId=null;render();}catch(error){showError(error.message);}});document.querySelector('#plannerCancelWeeklyEvent')?.addEventListener('click',()=>{state.editingEventId=null;render();});document.querySelectorAll('.weekly-edit-event').forEach(button=>button.addEventListener('click',()=>{state.editingEventId=button.dataset.id;render();}));document.querySelectorAll('.weekly-delete-event').forEach(button=>button.addEventListener('click',async()=>{if(!window.confirm(shared.tr('确定删除这项日程吗？','Delete this scheduled block?')))return;try{await apply([{type:'delete_event',id:button.dataset.id}]);if(state.editingEventId===button.dataset.id)state.editingEventId=null;}catch(error){showError(error.message);}}));}
  window.NorthstarPlannerWeekly={render,bind,weekEvents};
}());
