(function () {
  const { escapeHtml, tr, request } = window.NorthstarPlannerShared;
  const badgeText = state => !state.configured ? tr('手动模式', 'MANUAL MODE') : !state.tested ? tr('LLM 未测试', 'LLM UNTESTED') : state.ok ? tr('LLM 已连接', 'LLM CONNECTED') : tr('LLM 错误', 'LLM ERROR');
  const badgeClass = state => !state.configured || (state.tested && !state.ok) ? 'warn' : '';
  const resultHtml = state => !state.tested ? `<div class="planner-llm-result muted">${tr('尚未执行连接测试。', 'Connection test has not run yet.')}</div>` : !state.ok ? `<div class="planner-llm-result failure"><b>${tr('LLM 测试失败', 'LLM test failed')}</b><small>${escapeHtml(state.error || tr('未知错误', 'Unknown error'))}</small></div>` : `<div class="planner-llm-result success"><b>${tr('LLM 已成功连接', 'LLM connected successfully')}</b><small>${tr('模型', 'Model')}: ${escapeHtml(state.model || 'unknown')} · ${tr('延迟', 'Latency')}: ${state.latencyMs ?? '—'}ms</small></div>`;
  function render(state) { return `<div class="panel planner-input-panel"><div class="panel-header"><div><div class="panel-title">${tr('自然语言更新', 'Natural-language update')}</div><div class="panel-subtitle">${state.configured ? tr('解析结果仍需确认后才写入。', 'Proposed changes still require confirmation.') : tr('本地模型尚未配置，可使用手动添加。', 'Local model is not configured; use manual entry.')}</div></div><span id="plannerLlmBadge" class="source-pill ${badgeClass(state)}"><i></i>${badgeText(state)}</span></div><textarea id="plannerNaturalInput" placeholder="${tr('例如：本周完成 Web 安全 Lab 的认证模块', 'For example: Finish the auth module this week')}" ></textarea><div class="planner-actions"><button class="primary-button" id="plannerInterpret" ${state.configured ? '' : 'disabled'}>${tr('解析并预览', 'Parse and preview')}</button><button class="ghost-button" id="plannerLlmTest" ${state.configured ? '' : 'disabled'}>${tr('测试本地 LLM', 'Test Local LLM')}</button></div><div id="plannerLlmTestResult">${resultHtml(state)}</div><div id="plannerPreview"></div></div>`; }
  function bind(state, apply, showError) {
    const update = () => { const badge = document.querySelector('#plannerLlmBadge'); const result = document.querySelector('#plannerLlmTestResult'); if (badge) { badge.className = `source-pill ${badgeClass(state)}`; badge.innerHTML = `<i></i>${badgeText(state)}`; } if (result) result.innerHTML = state.testing ? `<div class="planner-llm-result muted">${tr('正在测试本地模型…', 'Testing the local model…')}</div>` : resultHtml(state); };
    document.querySelector('#plannerLlmTest')?.addEventListener('click', async () => { if (!state.configured || state.testing) return; state.testing = true; update(); try { const result = await request('/api/planner/llm-test', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); Object.assign(state, { tested: true, ok: true, model: result.model, latencyMs: result.latencyMs, error: null }); } catch (error) { Object.assign(state, { tested: true, ok: false, error: error.message }); } finally { state.testing = false; update(); } });
    document.querySelector('#plannerInterpret')?.addEventListener('click', async () => { const input = document.querySelector('#plannerNaturalInput').value.trim(); const preview = document.querySelector('#plannerPreview'); if (!input || !preview) return; preview.innerHTML = `<div class="planner-preview">${tr('正在请求本地模型…', 'Requesting the local model…')}</div>`; try { const result = await request('/api/planner/interpret', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ input }) }); preview.innerHTML = `<div class="planner-preview"><b>${tr('解析结果', 'Parsed result')}</b><pre>${escapeHtml(JSON.stringify(result.operations, null, 2))}</pre>${result.operations.length ? `<button class="primary-button" id="plannerConfirm">${tr('确认写入', 'Confirm and save')}</button>` : ''}</div>`; document.querySelector('#plannerConfirm')?.addEventListener('click', async () => { try { await apply(result.operations, true); } catch (error) { showError(error.message); } }); } catch (error) { showError(error.message); } });
  }
  window.NorthstarPlannerLlm = { render, bind };
}());
